GET http://localhost:2500/api/users
# GET http://localhost:2500/api/users

###

GET http://localhost:2500/api/users/63ca206e95d57aed0be5b5bb
# GET http://localhost:2500/api/users/63a64d9ba62108b75838c7f0


### 

POST http://localhost:2500/api/users/
Content-Type: application/json

{
  "name": "Pinky",
  "password": "Persimmon88!"
}

###

DELETE http://localhost:2500/api/users/63ca206e95d57aed0be5b5bb

###

PATCH  http://localhost:2500/api/users/63ca206e95d57aed0be5b5bb
Content-Type: application/json

{
  "name": "Mark"
}