GET http://localhost:2500/api/items
# GET http://localhost:2500/api/users

###

GET http://localhost:2500/api/users/63daa35eb466822a747efd0c
# GET http://localhost:2500/api/users/63a64d9ba62108b75838c7f0


### 

POST http://localhost:2500/api/users/
Content-Type: application/json

{
  "name": "Pinky",
  "password": "EasyPassword1234"
}

###

DELETE http://localhost:2500/api/users/63ca206e95d57aed0be5b5bb

###

PATCH  http://localhost:2500/api/items/63ddd3b7c4d17ee526044507
Content-Type: application/json

{
  "title": "Joystick",
  "image": "image",
  "description": "2sdfsdv",
  "platform": "Xbox",
  "price": "234",
  "owner": "Markjust"
}